version: "3"
# volumes:
#   postgis-data:

services:
  api:
    container_name: api
    build: ./app
    # dont set volumes if the WORKDIR is set in the Dockerfile
    # but do set volumes if you want hot-reload!
    volumes:
      - ./app:/usr/app     # all files/folders will be mapped 
      - /usr/app/node_modules # node_modules will not be mapped b/w the host computer and the container
    command: npm run start:dev
    depends_on:
      - postgis
    # secrets are in a .env file
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgis:5432/reddit_newsletter    
      SENDGRID_API_KEY: ${SENDGRID_API_KEY} 
    ports:
      - 5000:5000

  postgis:
    container_name: postgis
    image: kartoza/postgis:12.0
    # volumes:
    #   - postgis-data:/var/lib/postgresql/data
    depends_on: 
      - liquibase
    environment:
      - POSTGRES_DB=reddit_newsletter
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,"uuid-ossp"
    restart: on-failure 
    ports:
      - 5432:5432   
          
  liquibase:
    container_name: liquibase
    build: ./db 
    environment:
      - LIQUIBASE_HOST=postgis
      - LIQUIBASE_DATABASE=reddit_newsletter
      - LIQUIBASE_USERNAME=postgres
      - LIQUIBASE_PASSWORD=postgres      