# docker-compose.yml
version: "3"
services:
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://node-app@postgres/reddis-newsletter      
    ports:
      - "5000:5000"
      - "9229:9229"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: node-app
      POSTGRES_DB: reddis-newsletter
      POSTGRES_PASSWORD: postgres